version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  base-directory: public
  files:
    - "**/*"
